Set-Location "C:\Users\ahmad\Desktop\trading-pro-max-full"
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$sessionLog = ".\logs\session_$stamp.log"
Start-Transcript -Path $sessionLog -Append | Out-Null
Write-Host ""
Write-Host "========================================"
Write-Host " TPM CENTRAL TERMINAL"
Write-Host " Repo: $((Get-Location).Path)"
Write-Host " Session Log: $sessionLog"
Write-Host "========================================"
Write-Host ""
Write-Host "استخدم هنا فقط الأوامر التي أرسلها لك."
Write-Host "لإيقاف التسجيل اكتب: Stop-Transcript"
Write-Host ""
